names_list = { ...
%    {'red-9' 'blue-7'}, ...
%    {'blue-1' 'red-5'}, ...
%    {'blue-5' 'red-3'}, ...
%    {'red-7' 'yellow-1'}, ...
%    {'red-5' 'blue-7'}, ...
%    {'yellow-2' 'purple-1'}, ...
%    {'green-2' 'red-5'}, ...  % PBM
%    {'green-2' 'purple-1'}, ... 
% {'street-3', 'street-5'}, ...
% {'nature-3' 'art'}, ...
% {'street-4' 'street-6'}, ...
% {'street-2' 'street-7'}, ...
% {'street-8' 'street-1'}, ...
% {'nature-7' 'street-4'}, ...
% {'nature-7' 'street-2'}, ...
% {'street-11' 'street-10'}, ...
% {'colors1' 'colors2'}, ...
% {'colors3' 'colors4'}, ...
% {'colors5' 'colors6'}, ...
% {'colors7' 'colors8'}, ...
% {'colors9' 'colors8'}, ...
% {'nature-7' 'street-1'}, ...
% {'street-2' 'street-4'}, ...
% {'colors1' 'street-1'}, ...
% {'colors2' 'street-2'}, ...
% {'colors3' 'street-3'}, ...
% {'colors4' 'nature-7'}, ...
% {'colors5' 'street-4'}, ...
% {'colors6' 'street-5'}, ...
% {'colors7' 'street-7'}, ...
% {'colors8' 'street-10'}, ...
% {'colors9' 'street-11'}, ...
% {'colors10' 'vegetable-9'}, ...
% {'nature-2' 'portrait-2'}, ...
% {'nature-3' 'vegetable-1'}, ...
% {'nature-4' 'vegetable-6'}, ...
% {'nature-5' 'vegetable-11'}, ...
% {'nature-6' 'vegetable-12'}, ...
 {'green-5' 'red-5'}, ...
 {'green-6' 'red-5'}, ...
 {'green-7' 'red-5'}, ...
 {'landscape-1' 'red-5'}, ...
    }; 
    
for it=1:length(names_list)
    
    names = names_list{it};
    disp(['------ ' names{1} '/' names{2} ' ------']);
    generateColorFigure;
end
